apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "twim-bot.fullname" . }}
data:
  config.toml: |-
    {{- $.Files.Get "files/config.toml" | nindent 4 }}
  project_template.md: |-
    {{- $.Files.Get "files/project_template.md" | nindent 4 }}
  report_template.md: |-
    {{- $.Files.Get "files/report_template.md" | nindent 4 }}
  section_template.md: |-
    {{- $.Files.Get "files/section_template.md" | nindent 4 }}

