---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "twim-bot.fullname" . }}
  labels:
    {{- include "twim-bot.labels" . | nindent 4 }}
data:
  BOT_PASSWORD: {{ .Values.config.botPassword | toString | b64enc }}
